[package]
name = "vgd"
version = "1.0.0"
edition = "2021"

[dependencies.vg-core]
path = "../vg-core"

[dependencies.clap]
version = "4.5.1"
features = [ "derive" ]

[dependencies.serde]
version = "1.0.197"
features = [ "derive" ]

[dependencies.ron]
version = "0.8.1"
