[package]
name = "vgd"
version = "1.0.0"
edition = "2021"

[dependencies.args]
path = "../lib/args-rs"

[dependencies.vg-core]
path = "../vg-core"

[dependencies.serde]
version = "1.0.197"
features = [ "derive" ]

[dependencies.ron]
version = "0.8.1"
